src/PartsUnlimitedWebsite/Models/OrderCostSummary.cs
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace PartsUnlimited.ViewModels
{
    public class OrderCostSummary
    {
        public string CartSubTotal { get; set; }
        public string CartShipping { get; set; }
        public string CartTax { get; set; }
        public string CartTotal { get; set; }
    }
}

src/PartsUnlimitedWebsite/Areas/Admin/Controllers/OrdersController.cs
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Microsoft.AspNetCore.Mvc;
using PartsUnlimited.Queries;
using PartsUnlimited.ViewModels;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace PartsUnlimited.Areas.Admin.Controllers
{
    public class OrdersController : AdminController
    {
        private readonly IOrdersQuery _ordersQuery;

        public OrdersController(IOrdersQuery ordersQuery)
        {
            _ordersQuery = ordersQuery;
        }

        public async Task<IActionResult> Index(string username, DateTime? start, DateTime? end, string invalidOrderSearch)
        {
            return View(await _ordersQuery.IndexHelperAsync(username, start, end, 10, invalidOrderSearch, true));
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", new { invalidOrderSearch = Request.Query["id"] });
            }

            var order = await _ordersQuery.FindOrderAsync(id.Value);

            if (order == null)
            {
                return RedirectToAction("Index", new { invalidOrderSearch = id.ToString() });
            }
            var itemsCount = order.OrderDetails.Sum(x => x.Quantity);
            var subTotal = order.OrderDetails.Sum(x => x.Quantity * x.Product.Price);
            var shipping = itemsCount * (decimal)5.00;
            var tax = (subTotal + shipping) * (decimal)0.05;
            var total = subTotal + shipping + tax;

            var costSummary = new OrderCostSummary
            {
                CartSubTotal = subTotal.ToString("C"),
                CartShipping = shipping.ToString("C"),
                CartTax = tax.ToString("C"),
                CartTotal = total.ToString("C")
            };

            var viewModel = new OrderDetailsViewModel
            {
                OrderCostSummary = costSummary,
                Order = order
            };

            return View(viewModel);
        }
    }
}

src/PartsUnlimitedWebsite/Controllers/OrdersController.cs
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PartsUnlimited.Queries;
using PartsUnlimited.Telemetry;
using PartsUnlimited.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace PartsUnlimited.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IOrdersQuery _ordersQuery;
        private readonly ITelemetryProvider _telemetry;

        public OrdersController(IOrdersQuery ordersQuery, ITelemetryProvider telemetryProvider)
        {
            _ordersQuery = ordersQuery;
            _telemetry = telemetryProvider;
        }

        public async Task<IActionResult> Index(DateTime? start, DateTime? end, string invalidOrderSearch)
        {
            var username = User.Identity.Name;

            return View(await _ordersQuery.IndexHelperAsync(username, start, end, 10, invalidOrderSearch, false));
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                _telemetry.TrackTrace("Order/Server/NullId");
                return RedirectToAction("Index", new { invalidOrderSearch = Request.Query["id"] });
            }
          
            var order = await _ordersQuery.FindOrderAsync(id.Value);
            var username = User.Identity.Name;

            // If the username isn't the same as the logged in user, return as if the order does not exist
            if (order == null || !String.Equals(order.Username, username, StringComparison.Ordinal))
            {
                _telemetry.TrackTrace("Order/Server/UsernameMismatch");
                return RedirectToAction("Index", new { invalidOrderSearch = id.ToString() });
            }

            // Capture order review event for analysis
            var eventProperties = new Dictionary<string, string>()
                {
                    {"Id", id.ToString() },
                    {"Username", username }
                };
            if (order.OrderDetails == null)
            {
                _telemetry.TrackEvent("Order/Server/NullDetails", eventProperties, null);
            }
            else
            {
                var eventMeasurements = new Dictionary<string, double>()
                {
                    {"LineItemCount", order.OrderDetails.Count }
                };
                _telemetry.TrackEvent("Order/Server/Details", eventProperties, eventMeasurements);
            }

            var itemsCount = order.OrderDetails.Sum(x => x.Quantity);
            var subTotal = order.OrderDetails.Sum(x => x.Quantity * x.Product.Price);
            var shipping = itemsCount * (decimal)5.00;
            var tax = (subTotal + shipping) * (decimal)0.05;
            var total = subTotal + shipping + tax;

            var costSummary = new OrderCostSummary
            {
                CartSubTotal = subTotal.ToString("C"),
                CartShipping = shipping.ToString("C"),
                CartTax = tax.ToString("C"),
                CartTotal = total.ToString("C")
            };

            var viewModel = new OrderDetailsViewModel
            {
                OrderCostSummary = costSummary,
                Order = order
            };

            return View(viewModel);
        }
    }
}

src/PartsUnlimitedWebsite/Controllers/RecommendationsController.cs
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PartsUnlimited.Models;
using PartsUnlimited.Recommendations;
using PartsUnlimited.WebsiteConfiguration;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace PartsUnlimited.Controllers
{
    public class RecommendationsController : Controller
    {
        private readonly IPartsUnlimitedContext _db;
        private readonly IRecommendationEngine _recommendation;
        private readonly IWebsiteOptions _option;

        public RecommendationsController(IPartsUnlimitedContext context, IRecommendationEngine recommendationEngine, IWebsiteOptions websiteOptions)
        {
            _db = context;
            _recommendation = recommendationEngine;
            _option = websiteOptions;
        }

        public async Task<IActionResult> GetRecommendations(string recommendationId)
        {
            if (!_option.ShowRecommendations)
            {
                return new EmptyResult();
            }

            var recommendedProductIds = await _recommendation.GetRecommendationsAsync(recommendationId);

            var productTasks = recommendedProductIds
                .Select(item => _db.Products.SingleOrDefaultAsync(c => c.RecommendationId == Convert.ToInt32(item)))
                .ToList();

            await Task.WhenAll(productTasks);

            var recommendedProducts = productTasks
                .Select(p => p.Result)
                .Where(p => p != null && p.RecommendationId != Convert.ToInt32(recommendationId))
                .ToList();

            return PartialView("_Recommendations", recommendedProducts);
        }
    }
}

src/PartsUnlimitedWebsite/Controllers/SearchController.cs
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Microsoft.AspNetCore.Mvc;
using PartsUnlimited.Search;
using System.Threading.Tasks;

namespace PartsUnlimited.Controllers
{
    public class SearchController : Controller
    {
        private readonly IProductSearch _search;

        public SearchController(IProductSearch search)
        {
            _search = search;
        }

        public async Task<IActionResult> Index(string q)
        {
            if (string.IsNullOrWhiteSpace(q))
            {
                return View(null);
            }

            var result = await _search.Search(q);

            return View(result);
        }
    }
}

src/PartsUnlimitedWebsite/Controllers/ShoppingCartController.cs
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Microsoft.AspNetCore.Antiforgery;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Primitives;
using PartsUnlimited.Models;
using PartsUnlimited.Telemetry;
using PartsUnlimited.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace PartsUnlimited.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IPartsUnlimitedContext _db;
        private readonly ITelemetryProvider _telemetry;
        private readonly IAntiforgery _antiforgery;

        public ShoppingCartController(IPartsUnlimitedContext context, ITelemetryProvider telemetryProvider, IAntiforgery antiforgery)
        {
            _db = context;
            _telemetry = telemetryProvider;
            _antiforgery = antiforgery;
        }

        //
        // GET: /ShoppingCart/

        public IActionResult Index()
        {
            var cart = ShoppingCart.GetCart(_db, HttpContext);

            var items = cart.GetCartItems();
            var itemsCount = items.Sum(x => x.Count);
            var subTotal = items.Sum(x => x.Count * x.Product.Price);
            var shipping = itemsCount * (decimal)5.00;
            var tax = (subTotal + shipping) * (decimal)0.05;
            var total = subTotal + shipping + tax;

            var costSummary = new OrderCostSummary
            {
                CartSubTotal = subTotal.ToString("C"),
                CartShipping = shipping.ToString("C"),
                CartTax = tax.ToString("C"),
                CartTotal = total.ToString("C")
            };


            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = items,
                CartCount = itemsCount,
                OrderCostSummary = costSummary
            };

            // Track cart review event with measurements
            _telemetry.TrackTrace("Cart/Server/Index");

            // Return the view
            return View(viewModel);
        }

        //
        // GET: /ShoppingCart/AddToCart/5

        public async Task<IActionResult> AddToCart(int id)
        {
            // Retrieve the product from the database
            var addedProduct = _db.Products
                .Single(product => product.ProductId == id);

            // Start timer for save process telemetry
            var startTime = System.DateTime.Now;

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(_db, HttpContext);

            cart.AddToCart(addedProduct);

            await _db.SaveChangesAsync(HttpContext.RequestAborted);

            // Trace add process
            var measurements = new Dictionary<string, double>()
            {
                {"ElapsedMilliseconds", System.DateTime.Now.Subtract(startTime).TotalMilliseconds }
            };
            _telemetry.TrackEvent("Cart/Server/Add", null, measurements);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }

        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveFromCart(Request request)
        {
            // Retrieve the current user's shopping cart
            var cart = ShoppingCart.GetCart(_db, HttpContext);

            // Get the name of the album to display confirmation
            var cartItem = await _db.CartItems
                .Where(item => item.CartItemId == request.Id)
                .Include(c => c.Product)
                .SingleOrDefaultAsync();

            string message;
            int itemCount;
            if (cartItem != null)
            {
                // Remove from cart
                itemCount = cart.RemoveFromCart(request.Id);

                await _db.SaveChangesAsync(request.CancellationToken);

                string removed = (itemCount > 0) ? " 1 copy of " : string.Empty;
                message = removed + cartItem.Product.Title + " has been removed from your shopping cart.";
            }
            else
            {
                itemCount = 0;
                message = "Could not find this item, nothing has been removed from your shopping cart.";
            }

            // Display the confirmation message

            var results = new ShoppingCartRemoveViewModel
            {
                Message = message,
                CartTotal = cart.GetTotal().ToString(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = request.Id
            };

            return Json(results);
        }
    }
}

src/PartsUnlimitedWebsite/Controllers/StoreController.cs
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using PartsUnlimited.Models;
using System;
using System.Linq;

namespace PartsUnlimited.Controllers
{
    public class StoreController : Controller
    {
        private readonly IPartsUnlimitedContext _db;
        private readonly IMemoryCache _cache;

        public StoreController(IPartsUnlimitedContext context, IMemoryCache memoryCache)
        {
            _db = context;
            _cache = memoryCache;
        }

        //
        // GET: /Store/

        public IActionResult Index()
        {
            var category = _db.Categories.ToList();

            return View(category);
        }

        //
        // GET: /Store/Browse?category=Brakes

        public IActionResult Browse(int categoryId)
        {
            // Retrieve Category category and its Associated associated Products products from database

            // TODO [EF] Swap to native support for loading related data when available
            var categoryModel = _db.Categories.Single(g => g.CategoryId == categoryId);
            categoryModel.Products = _db.Products.Where(a => a.CategoryId == categoryModel.CategoryId).ToList();

            return View(categoryModel);
        }

        public IActionResult Details(int id)
        {
            Product productData;

            productData = _db.Products.Single(a => a.ProductId == id);
            productData.Category = _db.Categories.Single(g => g.CategoryId == productData.CategoryId);


            return View(productData);
        }
    }
}

src/PartsUnlimitedWebsite/Views/Shared/DemoLinkDisplay.cshtml
@{
    ViewBag.Title = "Demo link display page - Not for production use";
}

<section>
    <h2>@ViewBag.Title</h2>
    <div class="row">
        <div class="col-md-6">
            <div>
                <p>
                    Demo link display page - Not for production use.
                </p>

                @if (ViewBag.Link != null)
                {
                    <p class="text-danger">
                        For DEMO only: You can click this link to confirm the email: [[<a href="@ViewBag.Link">link</a>]]
                        <br />
                        Please change this code to register an email service in IdentityConfig to send an email.
                    </p>
                }
            </div>
        </div>
        <div class="col-md-6"></div>
    </div>
</section>

src/PartsUnlimitedWebsite/Views/Shared/_AdminMenu.cshtml
@using PartsUnlimited.Areas.Admin

@{
    var claims = User.Identity as System.Security.Claims.ClaimsIdentity;
    var isAdmin = claims.HasClaim(AdminConstants.ManageStore.Name, AdminConstants.ManageStore.Allowed);
}

@if (isAdmin)
{
    <li class="dropdown">
        <a href="@Url.Action("Index", "Store")" id="admin-link" class="dropdown-toggle head-link" data-toggle="dropdown">Admin&nbsp;<br class="hidden-xs" /><b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li> @Html.ActionLink("Manage Items", "Index", "StoreManager", new { area = AdminConstants.Area }) </li>
            <li> @Html.ActionLink("View Orders", "Index", "Orders", new { area = AdminConstants.Area }) </li>
            <li> @Html.ActionLink("Find Customers", "Find", "Customer", new { area = AdminConstants.Area }) </li>
            <li> @Html.ActionLink("View Rainchecks", "Index", "Raincheck", new { area = AdminConstants.Area }) </li>
        </ul>
    </li>

    <script>
        $(document).ready(function(){
            $(".dropdown-toggle").dropdown("toggle");
        });
    </script>
}

src/PartsUnlimitedWebsite/Views/Shared/_Layout.cshtml
@using System.Globalization
@using PartsUnlimited
@using Microsoft.DotNet.InternalAbstractions

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="Icon" href="/images/favicon.ico" />
    <title>@ViewBag.Title – Parts Unlimited</title>
    @await Component.InvokeAsync("Configuration") 

</head>
<body>
    <header>
        <nav class="navbar navbar-default">
            <div class="container">
                <div class="primary-menu">
                    <div class="pull-left logo">
                        <a class="block logo-image" href="@Url.Action("Index", "Home")">
                            <img src="/images/unlimited_logo.png"/>
                        </a>
                        <a class="block" href="@Url.Action("Index", "Home")">
                            <h1>Parts Unlimited</h1>
                            <h2>a Fabrikam subsidiary</h2>
                        </a>
                        <div class="visible-xs cart">
                            <a href="@Url.Action("Index", "ShoppingCart")" class="head-link" id="shopping-cart-link"></a>
                        </div>
                    </div>
                    <div class="pull-right navigation">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse-header-nav">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div class="collapse navbar-collapse" id="collapse-header-nav">
                            <ul class="nav navbar-nav navbar-right">
                                <li class="hidden-xs">
                                    <div id="search-link-box">
                                        @using (Html.BeginForm("Index", "Search", FormMethod.Get))
                                        {
                                            @Html.TextBox("q", null, new { @class = "form-control", id = "search-box", placeholder = "Keyword" })
                                            <input type="submit" id="search-link" value="Search" />
                                        }
                                    </div>
                                </li>
                                <li><a href="@Url.Action("Index", "Home")" class="head-link" id="home-link">Home</a></li>
                                @await Component.InvokeAsync("CartSummary")
                                @await Html.PartialAsync("_AdminMenu")
                                @await Html.PartialAsync("_Login")
                                <li class="dropdown visible-xs">
                                    <a href="@Url.Action("Index", "Store")" class="dropdown-toggle head-link" data-toggle="dropdown">Categories&nbsp;<b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        @await Component.InvokeAsync("CategoryMenu")
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="category-menu">
                <div class="container">
                    <div class="hidden-xs">
                        <ul>
                            @await Component.InvokeAsync("CategoryMenu")
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
        <div class="visible-xs search-box">
            @using (Html.BeginForm("Index", "Search", FormMethod.Get))
            {
                @Html.TextBox("q", null, new { @class = "form-control", placeholder = "Search" })
                <input type="submit" value="" />
            }
        </div>
    </header>
    @RenderSection("prebody", false)
    <div class="container">
        @RenderBody()
    </div>
    <div class="clearfix"></div>
    <footer>
        <div class="container">
            <div class="footer-content">
                <div class="row">
                    <div class="col-md-3">
                        <h4>Site Menu</h4>
                        <ul>
                            <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                            <li><a href="@Url.Action("Index", "Store")">Browse</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <h4>Account</h4>
                        <ul>
                            <li>@Html.ActionLink("Manage Account", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })</li>
                            <li>@Html.ActionLink("Shopping Cart", "Index", "ShoppingCart")</li>
                            <li>@Html.ActionLink("View Orders", "Index", "Orders", new { Area = string.Empty })</li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <h4>Additional Info</h4>
                        <ul>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">Terms and Conditions</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <h4>Develop</h4>
                        <ul>
                            <li><a>GitHub Source</a></li>
                            <li><a>License Agreement</a></li>
                            <li><a href="http://asp.net/" target="_blank">ASP.NET</a></li>
                        </ul>
                        <p>Deploy to Azure</p>
                        <a class="deploy-azure">
                            <img src="/images/deploy_button.png"/>
                        </a>
                    </div>
                </div>
                <hr />
                <div class="row">
                    <div class="col-md-6">
                        <div class="pull-left-sm">
                            © @DateTime.UtcNow.Year Microsoft. Based on The Phoenix Project by <a href="http://www.realgenekim.me/" class="footer-link">Gene Kim</a>.
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="pull-left-sm pull-right-md">
                            All rights reserved. Your payments are safe and secure.
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="text-center">
                        Site powered by @RuntimeEnvironment.OperatingSystem @RuntimeEnvironment.OperatingSystemVersion
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <link href="/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="/Content/Home.css" rel="stylesheet" type="text/css" />
    <link href="/Content/Account.css" rel="stylesheet" type="text/css" />
    <link href="/Content/ShoppingCart.css" rel="stylesheet" type="text/css" />
    <link href="/Content/Store.css" rel="stylesheet" type="text/css" />
    <link href="/lib/bootstrap/css/bootstrap.css" rel="stylesheet" type="text/css"/>
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jquery-zoom/jquery.zoom.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/respond/respond.src.js"></script>
    @RenderSection("scripts", required: false)

</body>
</html>

src/PartsUnlimitedWebsite/Views/Shared/_Login.cshtml
@if (User.Identity.IsAuthenticated)
{
    var isNtlm = User.Identity.AuthenticationType == "NTLM";
    
    <li class="dropdown">
        <a href="@Url.Action("Index", "Store")" id="profile-link" class="dropdown-toggle head-link" data-toggle="dropdown">Profile&nbsp;<br class="hidden-xs" /><b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li>@Html.ActionLink("Manage Account", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })</li>
            <li>@Html.ActionLink("View Orders", "Index", "Orders", new { Area = string.Empty })</li>
            @if (!isNtlm)
            {
            <li>
                @*Either NTLM will be used or social authentication will be used. Based on the authentication schemes enabled remove an unused block.*@
                @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                {
                    @Html.AntiForgeryToken()
                }
                <a href="javascript:document.getElementById('logoutForm').submit()" >Log off</a>
            </li>
            }
        </ul>
    </li>
}
else
{
    <li>@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "login-link", @class = "head-link" })</li>
}

src/PartsUnlimitedWebsite/Views/Shared/_OrdersSearch.cshtml
@model PartsUnlimited.ViewModels.OrdersModel

<div id="order-history-page">
    <section>
        <h2>Order History</h2>

        <div class="row">
            <div class="col-md-6 col-border-md-right">
                <h4>Search By Date</h4>

                @using (Html.BeginForm("Index", "Orders", FormMethod.Get))
                {
                    @if (Model.IsAdminSearch)
                    {
                        <div class="row form-group">
                            <div class="col-xs-12 col-sm-12 col-md-3 text-right-md">
                                <label for="inputfield1" class="control-label">Username</label>
                            </div>
                            <div class="col-xs-12 col-sm-8 col-md-7">
                                <input type="text" class="form-control" name="username" value="@Model.Username" placeholder="Username"  />
                            </div>
                        </div>
                    }

                    <div class="row form-group">
                        <div class="col-xs-12 col-sm-12 col-md-3 text-right-md">
                            <label for="inputfield1" class="control-label">Start date</label>
                        </div>
                        <div class="col-xs-12 col-sm-8 col-md-7">
                            <input type="text" class="form-control jquery-ui-datepicker" name="start" value="@Model.StartDate.ToString("d")" />
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-xs-12 col-sm-12 col-md-3 text-right-md">
                            <label for="inputfield1" class="control-label">End date</label>
                        </div>
                        <div class="col-xs-12 col-sm-8 col-md-7">
                            <input type="text" class="form-control jquery-ui-datepicker" name="end" value="@Model.EndDate.ToString("d")" />
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-sm-8 col-md-10">
                            <input type="submit" class="btn" value="Search" />
                        </div>
                    </div>
                }
            </div>
            <div class="col-md-6 wide-col-padding">
                <h4>Search By Order Number</h4>

                <div class="row form-group">
                    @using (Html.BeginForm("Details", "Orders", FormMethod.Get))
            {
                        <div class="col-sm-8 col-md-10">
                            <input type="text" class="form-control" id="name" name="id" placeholder="Order number" />
                            <input class="btn" type="submit" value="Open" />
                        </div>
                    }
                </div>
            </div>
        </div>
    </section>

    <section class="section-alt">
        @if (Model.Orders.Any())
        {

            @foreach (var order in Model.Orders)
            {
                <div class="row border order">
                    <div class="col-xs-12 col-sm-3 order-summary">
                        <div>Order Number: #@order.OrderId</div>
                        <div>Order Date: @order.OrderDate.ToString("d")</div>
                        <div><a href="@Url.Action("Details", "Orders", new { id = order.OrderId })" class="action-link">View order details</a></div>
                    </div>
                    <div class="col-xs-12 col-sm-9 order-detail">
                        <div class="row">
                            @foreach (var orderDetail in order.OrderDetails)
                            {
                                <div class="col-xs-12 order-detail-item">
                                    <h4><strong>@orderDetail.Quantity x @orderDetail.Product.Title</strong></h4>
                                    <p>@orderDetail.UnitPrice</p>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            }
        }
        else
        {
            <div class="alert alert-warning">
                No orders were found matching the criteria.
            </div>
        }
    </section>
</div>

src/PartsUnlimitedWebsite/Views/Shared/_Recommendations.cshtml
@model IEnumerable<PartsUnlimited.Models.Product>

@if (Model.Any())
{
        <h2>You may also consider</h2>
        @await Html.PartialAsync("_ProductList", Model)
}